app:
  name: "static-file-server"
  version: "1.0.0"

http:
  port: "8081"
  jwt_secret: "secret"

logger:
  log_level: "info"

postgres:
    pg_dsn: "host=localhost user=root password=password dbname=test port=5432 sslmode=disable TimeZone=Asia/Tehran"

minio:
  endpoint: "localhost:9000"
  access_key_id: "iyX7q2TomYovENNN5w20"
  secret_access_key: "qIChx85gHBheLr3lYe4g7uaP7L8mPFAdRakOJrko"
  use_ssl: false

image_optimization:
  large_image_width: 1920
  medium_image_width: 1280
  thumbnail_image_width: 200
  compression_quality: 80
  image_format: 3
  image_max_size: 200